In [ ]:
#q1
s={"aman","222",777,400.4}
t=tuple(s)
print(t)

In [ ]:
#q2
dict = {'rollno':[20227,20234,20209] ,'fname': ['kanishk','arvind','laxman'] , 'lastname': ['aadhaw','balaji','kr'] , 'dob': '2002-09-19' }
print(dict)

In [ ]:
#q3
import numpy as np
t=int(input())
np.random.seed(t)
arr=np.random.random((2,2))
print(arr)


In [ ]:
#q4
import numpy as np
arr=np.random.randint( low=0.0 , high=1.0 , size=1)
print(arr)
print(abs(-1234))

In [ ]:
#q5
import numpy as np
arr=np.random.randint( low=20 , high=90 , size=1,dtype=int)
print(arr)

In [ ]:
#q6
import random
set={11,12,13,14,15}
d=tuple(set)
a=random.sample(set,3)
print(a)
b=random.sample(set,5)
print(b)
l=random.choice(d)
print(l)

In [75]:
#q7
str="The King is Dead, Long Live The King"
fi=open("D:\\fil.txt","w")
fi.close()
fi=open("D:\\fil.txt","r")
print(fi.read())



The King is Dead, Long Live The King


In [3]:
#q8
price = 50
quantity = 5
amount = price*quantity

if amount > 100:
    if amount > 500:
        print("Amount is greater than 500")
    else:
        if amount < 500 and amount > 400:
            print("Amount is between 500 and 400")
        elif amount < 500 and amount > 300:
            print("Amount is between 300 and 500")
        else:
            print("Amount is between 200 and 500")
elif amount == 100:
    print("Amount is 100")
else:
    print("Amount is less than 100")

for x in range(10,20):
		if(x==15):break
               
		#if(x%5==0):
        #continue
		print(x)

x=0
#define a while loop
while(x<4):
		print(x)
		x=x+1

Amount is between 200 and 500
10
11
12
13
14
0
1
2
3


In [80]:
#q9
str="The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[3:5])
print(str[3:])
print(str.split())


The King is Dead, Long Live The King
T
 K
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [85]:
#q10
import numpy as np
li=[1,4,5,8]
arr=np.array(li)
print(arr[0:2])

[1 4]


In [87]:
#q11
import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [100]:
#q12
import numpy as np
arr=np.array(([1,2,3],[4,5,6]))
print(arr[1])
print(arr[0:2,1])
print(len(arr))

[4 5 6]
[2 5]
2


In [105]:
#q13
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
a=arr.reshape(5,2)
print(a)
print(a.transpose())

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


In [106]:
#q14
import numpy as np
li=[1,2,3]
arr=np.array(li)
print(arr)


[1 2 3]


In [ ]:
#q15
import numpy as np
arr=np.array([1,2,3])


In [107]:
#q16
import numpy as np
arr=np.array([2,4,5])
print(arr.sum())

11


In [108]:
#q17
import numpy as np
arr=np.array([77,74,75])
print(arr.prod())

427350


In [111]:
#q18
import numpy as np
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(arr.mean())
print(arr.var())
print(arr.max())
print(arr.min())
print(arr.argmin())
print(np.median(arr))
print(arr.argmax())
print(arr.std())

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


In [113]:
#q19
import numpy as np
arr=np.array([1,1,4,5,5,7])
li=[]
for i in arr:
    if i not in li:
        li.append(i)
li.sort()
print(li)


[1, 4, 5, 7]


In [112]:
#q20
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([0,1,1])
a=arr1*arr2
print(a)

[0 2 3]


In [118]:
#q21
import numpy as np
from numpy.linalg import eig
a=np.array(([2,-15],[1,-5]))
ei,ev=eig(a)
print(ei)
print(ev)

[-1.5+1.6583124j -1.5-1.6583124j]
[[0.96824584+0.j        0.96824584-0.j       ]
 [0.22592403-0.1070436j 0.22592403+0.1070436j]]


In [122]:
#q22
import numpy as np
a=np.array(([11,22,11,31],[25,33,31,28]))
convertedArray = a.astype(float)
r=np.corrcoef(a[0],a[1])
l=np.correlate(a[0],a[1])
print(r)
print(l)

[[1.         0.15997968]
 [0.15997968 1.        ]]
[2210]
